### ISSUE TITLE
Wrong tstamp formatting

### ISSUE THREAD

**Issue by chris246** [kartolo/direct_mail_subscription#13]
When using direct_mail_subscription 2.0.3 with tt_address 3.2.1, the tstamp shown in the recipient list in the Typo3 Backend is displayed as UNIX timestamp (e.g. 1425567589) instead of a correctly formatted date.
May be related to: #9

**Comment by kartolo** [comment]
somehow the tt_address TCA definition of tstamp field is set to passthrough. See https://github.com/FriendsOfTYPO3/tt_address/commit/ffdf590d53e6bc7a7f1c6252bc75c1d48bd049dc

please report this to tt_address
