### ISSUE TITLE
Error: Could not scan for classes inside "/var/www/html/typo3conf/ext/direct_mail_subscription/Classes/"

### ISSUE THREAD

**Issue by seirerman** [kartolo/direct_mail_subscription#18]
Everytime I install or uninstall an extension in the extension manager, I get an error:

`Could not scan for classes inside "/var/www/html/typo3conf/ext/direct_mail_subscription/Classes/" which does not appear to be a file nor a folder`

And after I uninstall an extension I have to delete the cache files manually after the previous error message, because it somehow prevents the cache to be cleared, and I end up with a "dead" installation and:

`TYPO3 Fatal Error: Extension key "[Extension name]" is NOT loaded!`

This might have something to do with https://forge.typo3.org/issues/76457

I'm on TYPO3 7.6.15, PHP 5.6.29 and direct_mail_subscription 2.0.3, by the way.

**Comment by whiteroom** [comment]
This has been corrected on commit 8792d07
Which basically meant adding the missing folder "Classes", since TYPO3 package manager scans Classes folder.
The real problem is, that the TYPO3 Extension Repository and this code repository are **NOT** in sync! So please fix #16 and #17 

Thank you

**Comment by kartolo** [comment]
closing this. new release will be made
