### ISSUE TITLE
Typo3.org Version 2.0.3 has Error in /direct_mail_subscription/Configuration/TCA/Overrides/tt_address.php

### ISSUE THREAD

**Issue by vimwb** [kartolo/direct_mail_subscription#19]
In the Typo3.org Version 2.0.3 the File "/direct_mail_subscription/Configuration/TCA/Overrides/tt_address.php" looks like this:

`<?php
if (!defined('TYPO3_MODE')) {
    die('Access denied.');
}

$GLOBALS['TCA']['tt_address']['feInterface']['fe_admin_fieldList'] .= ',name';
`

This leads to an error because "email is missing

In the Github Version it is korrekt:

`<?php
if (!defined('TYPO3_MODE')) {
    die('Access denied.');
}

$GLOBALS['TCA']['tt_address']['feInterface']['fe_admin_fieldList'] .= ',hidden,gender,name,email,first_name,last_name,company';
`

**Comment by kartolo** [comment]
will release 2.0.4. see #16
