### ISSUE TITLE
TYPO3 v8 LTS (8.7) compatibility

### ISSUE THREAD

**Issue by christianriesche** [kartolo/direct_mail_subscription#25]
Would be great if you could make it compatible with the latest LTS release.

**Comment by oliverschloebe** [comment]
+1

**Comment by rawsta** [comment]
+1

**Comment by arunspt** [comment]
Hi, Any updates for this? Thanks for the help.

**Comment by webdev2027** [comment]
Hi, the compatibility would be great!  At the moment, there's no extension for (direct_mail-)subscription available (nov 2017).

**Comment by GhanshyamBhava** [comment]
I facing the same issue in v TYPO3 8.7.8. I have completely follow configuration steps. But, subscription form still not rendering in FE. It would be great if maintain extension for v 8.7.

**Comment by christianriesche** [comment]
Meanwhile you can handle subscription in TYPO3 8.7 with this fork of ods_ajaxmailsubscription:
https://github.com/christianriesche/ods_ajaxmailsubscription

**Comment by rsternec** [comment]
I would be glad about compatibility, too. Is there some progress on this topic?

**Comment by webdev2027** [comment]
Hi. the fork (https://github.com/christianriesche/ods_ajaxmailsubscription) is a nice idea, but the extension "ods_ajaxmailsubscription" is very old ...

Hopefully the update will come in the next few weeks ..

**Comment by kartolo** [comment]
I'm working on it, please stand by. Anybody willing to help testing?

**Comment by kartolo** [comment]
please test #29. I don't have time to recheck this on 7.6 LTS. If anyone could check it on 7.6 LTS, would be really great.

Please give some feedback so I can merge it and release to TER. Thanks

**Comment by angeloprevitali** [comment]
I tried the https://github.com/kartolo/direct_mail_subscription/pull/29 to test it on a TYPO3 CMS version 8.7.10 and get this error after calling up the page with the plug-in on the FE:

`Fatal error: Uncaught InvalidArgumentException: There is no entry in the $TCA array for the table "sys_dmail_category". This means that the function enableFields() is called with an invalid table name as argument. in /typo3/sysext/frontend/Classes/Page/PageRepository.php:1456 Stack trace: #0 /typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(6738): TYPO3\CMS\Frontend\Page\PageRepository->enableFields('sys_dmail_categ...', false, Array) #1 /typo3conf/ext/direct_mail_subscription/pi/class.dmailsubscribe.php(129): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->enableFields('sys_dmail_categ...') #2 [internal function]: user_dmailsubscribe->makeCheckboxes('', Array) #3 /typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(6330): call_user_func_array(Array, Array) #4 /typo3/sysext/frontend/Classes/Page/PageRepository.php on line 1456 `

Daes it helps you somehow?

Regards,
Angelo

**Comment by rsternec** [comment]
#29 works for me as I do not use categories (see Angelos post), but I have to include the pull request #24 'Compatibility with captcha'. If not, captcha is shown but never correct. So you should merge #24 before.

**Comment by sebkln** [comment]
Hey, great you work on compatibility with TYPO3 v8.

When using #29 in combination with #24 and #32, subscription works in general. The data is saved, the emails get sent. I only found a minor issue:

- Some `tt_address` fields (e.g. _address_ or _city_) can't be filled with the subscription or edit form. This is caused by the usage of `fe_admin_fieldList` for the list of writable fields. This list was shortened in TYPO3 core. For now I extend this list with the needed fields directly in my sitepackage extension (`Configuration/TCA/Overrides/tt_address.php`), which is fine.

Edit: Forget about my second issue with duplicate mail content. I had two subscribers using the same email address (one being a test user in a different folder). This caused duplicate mail bodys when requesting the `FORGOTPASSWORD` mail.

**Comment by mz-aimcom** [comment]
Hi, thanks for your work!
The [`feature/25_lts_compatibility`](https://github.com/kartolo/direct_mail_subscription/tree/feature/25_lts_compatibility) works for me in my TYPO3 8.7.19 environment. There is only one debug line that should be removed: [fe_adminLib.php, Line 920](https://github.com/kartolo/direct_mail_subscription/blob/feature/25_lts_compatibility/Classes/fe_adminLib.php#L920).
Do you already have a clue when the feature will make it into `master`?

_Update:_ I had another change (see below and [in pull request #35](https://github.com/kartolo/direct_mail_subscription/pull/35)).

**Comment by chris246** [comment]
Hi, when will this be released?
From December 1st, TYPO3 v7 will no longer receive regular bugfixes, so those installations should be updated soon.
