### ISSUE TITLE
Typo3 v9 compatibility

### ISSUE THREAD

**Issue by nollm** [kartolo/direct_mail_subscription#33]
It would be great to have compatibility with Typo3 v9. Are you planing to do this?

**Comment by kevinlieser** [comment]
Try this fork from me https://github.com/kevinlieser/direct_mail_subscription
Just edited to work with TYPOO3 9.5 – no rebuild!

**Comment by chrcan** [comment]
the ext can be installed with TYPO3 9.5.13 but I can not select the plugin in the content?

**Comment by kevinlieser** [comment]
Which one? This one or my fork?

**Comment by chrcan** [comment]
your fork @kevinlieser

**Comment by kevinlieser** [comment]
Then you should post an issue at the fork. Did you cleared all caches?

**Comment by chrcan** [comment]
@kevinlieser i dont can make an issue on your fork https://github.com/kevinlieser/direct_mail_subscription

**Comment by kevinlieser** [comment]
Oh sorry, now you can!

**Comment by nollm** [comment]
I don't think this extension will be developed any further.
There are some alternatives in the [Extension Repository](https://extensions.typo3.org/?tx_solr[q]=newsletter+subscribe) of Typo3.
