### ISSUE TITLE
Missing argument in getParsedData()

### ISSUE THREAD

**Issue by msollmann** [kartolo/direct_mail_subscription#6]
After updating from 2.0.2 to 2.0.3 I got this FE error:

Uncaught TYPO3 Exception
#1: PHP Warning: Missing argument 4 for

TYPO3\CMS\Core\Localization\LocalizationFactory::getParsedData(), called in
/typo3conf/ext/direct_mail_subscription/pi/class.dmailsubscribe.php on line
281 and defined in
/staeqwbx/typo3_src-6.2.21/typo3/sysext/core/Classes/Localization/LocalizationFactory.php
line 78

I changed the line from:
$this->LOCAL_LANG = $languageFactory->getParsedData($basePath, $this->LLkey,
$GLOBALS['TSFE']->renderCharset);

to:

$this->LOCAL_LANG = $languageFactory->getParsedData($basePath, $this->LLkey,
$GLOBALS['TSFE']->renderCharset, **1**);

and it worked. The 4th parameter is not optional.

TYPO3 6.2.21

**Comment by kartolo** [comment]
it seems that third and fourth parameter in 6.2 are not optional. Fix is coming
