### ISSUE TITLE
Empty records with tt_address 3.1.1

### ISSUE THREAD

**Issue by msollmann** [kartolo/direct_mail_subscription#9]
Ext:direct_mail_subscription creates empty records when using together with Ext:tt_address 3.1.1, since tt_address does not set the deprecated feInterface.fe_admin_fieldList anymore. This results in an empty (or shortened) fieldList in direct_mail_subscription/fe_adminLib.inc, line 185: $this->fieldList = implode(',', GeneralUtility::trimExplode(',', $GLOBALS['TCA'][$this->theTable]['feInterface']['fe_admin_fieldList'], 1));

**Comment by Queron81** [comment]
I have a similar problem. Direct Mail Subscription is not working with tt_address >= 3.1.x . When you want to subscribe, you get this error:

> address in mailbox given [] does not comply with rfc 2822 3.6.2

Subscription is saved in the tt_address table, but without the email address. Installing tt_address 3.0.3 again solves this problems.

**Comment by msollmann** [comment]
It's the same problem. It results in the cited error.

**Comment by nsd0sproffe** [comment]
tt_address doesn't provide $GLOBALS['TCA']['tt_address']['feInterface']['fe_admin_fieldList'] any longer.
Please add email to the fieldlist in Configuration/TCA/Overrides/tt_address.php in line 6. Like so:
`$GLOBALS['TCA']['tt_address']['feInterface']['fe_admin_fieldList'] .= ',name,email';`

**Comment by KiddsOrange** [comment]
Do the same with the field "hidden", like:
$GLOBALS['TCA']['tt_address']['feInterface']['fe_admin_fieldList'] .= ',name,email,hidden';
Otherwise the user's address is active directly after registration, without confirmation.
